### ISSUE TITLE
hadolint ignore=DL3008

### ISSUE THREAD

**Issue by davidgatti** [0x4447-setup/0x4447_docker#24]
Is this `# hadolint ignore=DL3008` necessary?

**Comment by vladpona** [comment]
Not removed. Better to have this code

**Comment by davidgatti** [comment]
@vladpona can you explain the purpose?

**Comment by vladpona** [comment]
@davidgatti The problem is with python vendor.
As you may know the python is top slow and unstable scripting language. But also top popular and fastest growing.
Sometimes vendor may change minor package version inside of distributive. For example I saw this behavior inside Debian 9. When the package version was changed from 2.5 to 2.7
This is not only "update" but switch to another branch. And it triggers warning (at APT in my case) with non-zero return code.
This is not a problem if you just interacting with OS. You just will see the warning like "W: package *** switched to another version". And the update process will be done.
But for docker every non-zero return inside of Dockerfile will break the installation.
So "hadolint ignore=xxx" - it's instructions to ignore such warnings and to continue installation process

**Comment by davidgatti** [comment]
Wooo, who knew :) thank you for the explanation.
