### ISSUE TITLE
Add the X server

### ISSUE THREAD

**Issue by davidgatti** [0x4447-setup/0x4447_docker#34]
I want to have a very basic X server setup mainly to host a chrome browser to be used to check suspicions website, so if something bad happens you kill the container, start a new one, and you have a fresh system again.

The general setup:

- Basic X server
- Chrome for the main browser
- A UI based file explorer
- connection using VNC or RDP whichever is the most secure. Ideally the connection should be encrypted.
- The configuration should always start at boot time.

**Comment by vladpona** [comment]
First release is ready. Probably there will be more issues later. But it works for me right now with minimal changes.
Just 1 change in building/running process:
Will be:
`docker run -p 3389:3389 -it -h docker 0x4447:latest`
Instead of previous:
`docker run -it -h docker 0x4447:latest`
It's for possibility of remote usage (e.g. deployment this docker to remote server). And for more comfortable usage on local OS. E.g. you can connect to 127.0.0.1:3389 instead of searching for which IP-address bond running docker image

And one note regarding RDP-clients to use.
1. I got most stability if I'm using `remmina` modern remote desktop client
2. Not so stable this works with `rdesktop` client. There is some issues with file manager stuck. And the client may be crashed sometimes without any adequate error message
3. It can be run under `freerdp2` client too. But stability there is weird. Probably this can be solved by some crafted command line flags combination. But I don't think this may have sense to waste time for that combination searching.

BTW. Probably there is sense to make this project as another branch? It's much bigger than current docker for command line usage. But of course it's up to you
